import path from "node:path";

import rehypeShikiFromHighlighter from "@shikijs/rehype/core";
import adapter from "@sveltejs/adapter-static";
import type { Config } from "@sveltejs/kit";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";
import type { Element, Text } from "hast";
import { escapeSvelte, mdsvex } from "mdsvex";
import { rehypeGithubAlerts } from "rehype-github-alerts";
import rehypeGithubColor from "rehype-github-color";
import rehypeGithubDir from "rehype-github-dir";
import rehypeGithubEmoji from "rehype-github-emoji";
import rehypeGithubHeading from "rehype-github-heading";
import rehypeGithubLink from "rehype-github-link";
import remarkDirective from "remark-directive";
import remarkFlexibleToc from "remark-flexible-toc";
import remarkGfm from "remark-gfm";
// @ts-expect-error: dts missing
import remarkGithubBreak from "remark-github-break";
import { createHighlighter } from "shiki";
import type { Plugin } from "unified";
import { visit } from "unist-util-visit";

const highlighter = await createHighlighter({
  themes: ["github-light", "github-dark"],
  langs: [
    "bash",
    "css",
    "diff",
    "dockerfile",
    "html",
    "javascript",
    "json",
    "jsonc",
    "markdown",
    "python",
    "rust",
    "sh",
    "shell",
    "svelte",
    "text",
    "toml",
    "typescript",
    "tsx",
    "yaml",
    "zsh",
  ],
});

// Rehype plugin to fix MDsveX's old remark-parse collapsing `[!NOTE]\n[link](url)`
// into a single text node `"[!NOTE][link]"` — which breaks rehype-github-alerts.
// When the broken pattern is detected, we reconstruct proper nodes so
// rehype-github-alerts sees `[!NOTE]\n` as required.
const rehypeFixAlertLink: Plugin = () => tree => {
  visit(tree, "element", node => {
    const el = node as Element;
    if (el.tagName !== "blockquote") return;

    for (const child of el.children) {
      if ((child as Element).tagName !== "p") continue;
      const p = child as Element;
      if (p.children.length === 0) continue;

      const first = p.children[0];
      if (first.type !== "text") continue;

      // Match "[!NOTE][link text]" — the collapsed broken form
      const match = first.value.match(/^(\[!(NOTE|TIP|WARNING|IMPORTANT|CAUTION)\])\[(.+)\]$/i);
      if (!match) continue;

      const alertMarker = match[1]; // e.g. "[!NOTE]"
      // Children after [0] should be: text "(", element <a href>, text ") rest..."
      const parenOpen = p.children[1];
      const autolink = p.children[2];
      const parenClose = p.children[3];

      if (
        parenOpen?.type !== "text" ||
        parenOpen.value !== "(" ||
        autolink?.type !== "element" ||
        autolink.tagName !== "a" ||
        parenClose?.type !== "text" ||
        !parenClose.value.startsWith(")")
      )
        continue;

      const href = (autolink.properties?.href as string) ?? "";
      const linkText = match[3];

      // Preserve any extra properties from the autogenerated <a> (e.g. rel: ['nofollow'])
      const reconstructed: Element = {
        type: "element",
        tagName: "a",
        properties: { ...autolink.properties, href },
        children: [{ type: "text", value: linkText }],
      };

      // Text after the closing ")" — trim the leading ")"
      const afterText = parenClose.value.slice(1);
      const remaining = p.children.slice(4);

      p.children = [
        { type: "text", value: `${alertMarker}\n` },
        reconstructed,
        ...(afterText ? [{ type: "text", value: afterText } as Text] : []),
        ...remaining,
      ];
    }
  });
};

const COPY_SVG =
  `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"` +
  ` fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"` +
  ` stroke-linejoin="round" aria-hidden="true" class="icon-copy">` +
  `<rect width="14" height="14" x="8" y="8" rx="2" ry="2"/>` +
  `<path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/>` +
  `</svg>`;

const CHECK_SVG =
  `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"` +
  ` fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"` +
  ` stroke-linejoin="round" aria-hidden="true" class="icon-check">` +
  `<path d="M20 6 9 17l-5-5"/>` +
  `</svg>`;

const SHIKI_OPTIONS = {
  themes: { light: "github-light", dark: "github-dark" },
  defaultColor: false,
} as const;

const config: Config = {
  // Consult https://svelte.dev/docs/kit/integrations
  // for more information about preprocessors
  preprocess: [
    /** @type {import('svelte/compiler').PreprocessorGroup} */ mdsvex({
      extensions: [".svx", ".md"],
      highlight: {
        highlighter: (code, lang) => {
          const active_lang =
            lang && highlighter.getLoadedLanguages().includes(lang) ? lang : "text";

          const pre_html = highlighter.codeToHtml(code, { ...SHIKI_OPTIONS, lang: active_lang });

          const badge_html =
            active_lang === "text" ? "" : `<span class="code-lang-badge">${active_lang}</span>`;

          const btn_html =
            `<button type="button" class="code-copy-btn" aria-label="Copy code">` +
            `${COPY_SVG}${CHECK_SVG}</button>`;

          const wrapper = `<div class="code-block-wrapper">${badge_html}${btn_html}${pre_html}</div>`;

          return `{@html \`${escapeSvelte(wrapper)}\`}`;
        },
      },
      remarkPlugins: [remarkDirective, remarkFlexibleToc as unknown as Plugin, remarkGfm],
      rehypePlugins: [
        rehypeFixAlertLink,
        rehypeGithubAlerts,
        rehypeGithubColor,
        rehypeGithubDir,
        rehypeGithubEmoji,
        rehypeGithubHeading,
        rehypeGithubEmoji,
        rehypeGithubLink,
        remarkGithubBreak,
        rehypeShikiFromHighlighter(highlighter, {
          ...SHIKI_OPTIONS,
          inline: "tailing-curly-colon",
          fallbackLanguage: "text",
        }),
      ],
      layout: {
        _: path.join(import.meta.dirname, "./src/lib/components/markdown/MarkdownLayout.svelte"),
      },
    }),
    vitePreprocess(),
  ],
  kit: {
    adapter: adapter({
      pages: "build",
      assets: "build",
      precompress: false,
      strict: true,
      fallback: "404.html",
    }),
    paths: {
      base: (process.argv.includes("dev") ? "" : process.env.BASE_PATH) as
        | ""
        | `/${string}`
        | undefined,
    },
    alias: {
      "$contents/*": path.join(import.meta.dirname, "src", "contents", "*"),
    },
  },
  extensions: [".svelte", ".svx", ".md"],
  compilerOptions: {
    experimental: {
      async: true,
    },
  },
};

export default config;
